"""Update mental axes to positive indicators

Revision ID: 01507bb61cc3
Revises: 0263704fadfa
Create Date: 2026-02-03 01:43:45.210330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01507bb61cc3'
down_revision: Union[str, None] = '0263704fadfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_usage_user_date', table_name='daily_usage')
    op.create_unique_constraint('uq_daily_usage_user_date', 'daily_usage', ['user_id', 'usage_date'])

    # Add new columns for mental_analyses
    op.add_column('mental_analyses', sa.Column('emotional_stability_score', sa.Integer(), nullable=True))
    op.add_column('mental_analyses', sa.Column('vitality_score', sa.Integer(), nullable=True))
    op.add_column('mental_analyses', sa.Column('resilience_score', sa.Integer(), nullable=True))

    # Migrate existing data for mental_analyses
    # emotional_stability = 100 - (stress + anxiety) / 2
    # vitality = 100 - depression
    # resilience = 50 (default, cannot infer from old data)
    op.execute("""
        UPDATE mental_analyses
        SET
            emotional_stability_score = GREATEST(0, LEAST(100, 100 - ((COALESCE(stress_score, 50) + COALESCE(anxiety_score, 50)) / 2))),
            vitality_score = GREATEST(0, LEAST(100, 100 - COALESCE(depression_score, 50))),
            resilience_score = 50
    """)

    # Drop old columns and indices
    op.drop_index('ix_mental_analyses_analysis_date', table_name='mental_analyses')
    op.drop_index('ix_mental_analyses_user_created', table_name='mental_analyses')
    op.drop_index('ix_mental_analyses_user_id', table_name='mental_analyses')
    op.drop_column('mental_analyses', 'stress_score')
    op.drop_column('mental_analyses', 'anxiety_score')
    op.drop_column('mental_analyses', 'depression_score')

    # Add new columns for mental_reports
    op.add_column('mental_reports', sa.Column('avg_emotional_stability_score', sa.Integer(), nullable=True))
    op.add_column('mental_reports', sa.Column('avg_vitality_score', sa.Integer(), nullable=True))
    op.add_column('mental_reports', sa.Column('avg_resilience_score', sa.Integer(), nullable=True))

    # Migrate existing data for mental_reports
    op.execute("""
        UPDATE mental_reports
        SET
            avg_emotional_stability_score = GREATEST(0, LEAST(100, 100 - ((COALESCE(avg_stress_score, 50) + COALESCE(avg_anxiety_score, 50)) / 2))),
            avg_vitality_score = GREATEST(0, LEAST(100, 100 - COALESCE(avg_depression_score, 50))),
            avg_resilience_score = 50
    """)

    # Drop old columns and indices
    op.drop_index('ix_mental_reports_user_id', table_name='mental_reports')
    op.drop_index('ix_mental_reports_user_type_period', table_name='mental_reports')
    op.drop_column('mental_reports', 'avg_depression_score')
    op.drop_column('mental_reports', 'avg_stress_score')
    op.drop_column('mental_reports', 'avg_anxiety_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mental_reports', sa.Column('avg_anxiety_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.add_column('mental_reports', sa.Column('avg_stress_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.add_column('mental_reports', sa.Column('avg_depression_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.create_index('ix_mental_reports_user_type_period', 'mental_reports', ['user_id', 'report_type', 'period_start'], unique=False)
    op.create_index('ix_mental_reports_user_id', 'mental_reports', ['user_id'], unique=False)
    op.drop_column('mental_reports', 'avg_resilience_score')
    op.drop_column('mental_reports', 'avg_vitality_score')
    op.drop_column('mental_reports', 'avg_emotional_stability_score')
    op.add_column('mental_analyses', sa.Column('depression_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.add_column('mental_analyses', sa.Column('anxiety_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.add_column('mental_analyses', sa.Column('stress_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.create_index('ix_mental_analyses_user_id', 'mental_analyses', ['user_id'], unique=False)
    op.create_index('ix_mental_analyses_user_created', 'mental_analyses', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_mental_analyses_analysis_date', 'mental_analyses', ['analysis_date'], unique=False)
    op.drop_column('mental_analyses', 'resilience_score')
    op.drop_column('mental_analyses', 'vitality_score')
    op.drop_column('mental_analyses', 'emotional_stability_score')
    op.drop_constraint('uq_daily_usage_user_date', 'daily_usage', type_='unique')
    op.create_index('ix_daily_usage_user_date', 'daily_usage', ['user_id', 'usage_date'], unique=False)
    # ### end Alembic commands ###
