"""add_subscription_and_character_tables

Revision ID: a7ba17d6e342
Revises: a1b2c3d4e5f6
Create Date: 2026-01-22 06:26:16.342581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ba17d6e342'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('style', sa.Enum('WATERCOLOR', 'ANIME', 'PIXEL', 'THREED', 'REALISTIC', 'CARTOON', name='characterstyle'), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('generation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PREMIUM', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('character_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('style', sa.Enum('WATERCOLOR', 'ANIME', 'PIXEL', 'THREED', 'REALISTIC', 'CARTOON', name='characterstyle'), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('diary_count_at_generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_history_id'), 'character_history', ['id'], unique=False)
    op.drop_index('ix_notifications_user_is_read', table_name='notifications')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.create_index('ix_notifications_user_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_character_history_id'), table_name='character_history')
    op.drop_table('character_history')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
